From: Zdenek Dohnal <zdohnal@redhat.com>
Date: Fri, 31 Jan 2020 13:40:10 +0100
Subject: Scanning broken for HP LaserJet 3052

Origin: https://src.fedoraproject.org/rpms/hplip/blob/master/f/hplip-hplj-3052.patch
---
 scan/scanext/scanext.c | 10 ----------
 1 file changed, 10 deletions(-)

diff --git a/scan/scanext/scanext.c b/scan/scanext/scanext.c
index 3ddfb35..1e6b514 100755
--- a/scan/scanext/scanext.c
+++ b/scan/scanext/scanext.c
@@ -408,16 +408,6 @@ static PyObject *setOption (_ScanDevice * self, PyObject * args)
     int n;
     multipick = 1;
 
-if(1)
-{
-SANE_Bool b = SANE_TRUE;
-    sane_control_option (self->h, 9, SANE_ACTION_SET_VALUE, (void *)&b, &i);
-}
-else
-{
-SANE_Bool b = SANE_FALSE;
-    sane_control_option (self->h, 9, SANE_ACTION_SET_VALUE, (void *)&b, &i);
-}
     if (!PyArg_ParseTuple (args, "iO", &n, &value))
         raiseError("Invalid arguments.");
 
